name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  archipelago-core-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@main
    with:
      service-name: archipelago-nats
      image-name: archipelago-nats
      deployment-environment: dev
    secrets: inherit
